import 'toll_charge_rule.dart';

/// Represents an itemized toll charge event generated by the calculation engine.
class TollChargeBreakdown {
  final String tollRuleId;
  final String expressway;
  final String operator; // "autosweep" or "easytrip"
  final String collectionType; // "closedSystem", "openBarrier", "fixedConnector"
  final String? entryPlazaId;
  final String? exitPlazaId;
  final String? chargedAtPlazaId;
  final int vehicleClass; // 1, 2, or 3
  final double amount;
  final String sourceName;
  final String? sourceUrl;
  final DateTime? effectiveFrom;
  final DateTime? ratesLastUpdated;
  DateTime? get lastVerified => ratesLastUpdated;
  final TollVerificationStatus verificationStatus;
  final String explanation;

  const TollChargeBreakdown({
    required this.tollRuleId,
    required this.expressway,
    required this.operator,
    required this.collectionType,
    this.entryPlazaId,
    this.exitPlazaId,
    this.chargedAtPlazaId,
    required this.vehicleClass,
    required this.amount,
    this.sourceName = 'TRB Official Toll Rate Matrix',
    this.sourceUrl,
    this.effectiveFrom,
    DateTime? lastVerified,
    DateTime? ratesLastUpdated,
    this.verificationStatus = TollVerificationStatus.verified,
    required this.explanation,
  }) : ratesLastUpdated = ratesLastUpdated ?? lastVerified ?? effectiveFrom;

  /// Whether this charge is officially verified against current TRB publications.
  bool get isVerified => verificationStatus == TollVerificationStatus.verified;

  Map<String, dynamic> toJson() {
    return {
      'tollRuleId': tollRuleId,
      'expressway': expressway,
      'operator': operator,
      'collectionType': collectionType,
      if (entryPlazaId != null) 'entryPlazaId': entryPlazaId,
      if (exitPlazaId != null) 'exitPlazaId': exitPlazaId,
      if (chargedAtPlazaId != null) 'chargedAtPlazaId': chargedAtPlazaId,
      'vehicleClass': vehicleClass,
      'amount': amount,
      'sourceName': sourceName,
      if (sourceUrl != null) 'sourceUrl': sourceUrl,
      if (effectiveFrom != null) 'effectiveFrom': effectiveFrom?.toIso8601String(),
      if (ratesLastUpdated != null) 'ratesLastUpdated': ratesLastUpdated?.toIso8601String(),
      if (lastVerified != null) 'lastVerified': lastVerified?.toIso8601String(),
      'verificationStatus': verificationStatus.name,
      'explanation': explanation,
    };
  }

  factory TollChargeBreakdown.fromJson(Map<String, dynamic> json) {
    DateTime? verifiedDate;
    if (json['lastVerified'] != null) {
      verifiedDate = DateTime.tryParse(json['lastVerified'].toString());
    }

    DateTime? effectiveDate;
    if (json['effectiveFrom'] != null) {
      effectiveDate = DateTime.tryParse(json['effectiveFrom'].toString());
    }

    TollVerificationStatus status = TollVerificationStatus.verified;
    if (json['verificationStatus'] != null) {
      status = TollVerificationStatus.values.firstWhere(
        (e) => e.name == json['verificationStatus'],
        orElse: () => TollVerificationStatus.needsManualReview,
      );
    }

    return TollChargeBreakdown(
      tollRuleId: json['tollRuleId'] as String? ?? '',
      expressway: json['expressway'] as String? ?? '',
      operator: json['operator'] as String? ?? '',
      collectionType: json['collectionType'] as String? ?? 'closedSystem',
      entryPlazaId: json['entryPlazaId'] as String?,
      exitPlazaId: json['exitPlazaId'] as String?,
      chargedAtPlazaId: json['chargedAtPlazaId'] as String?,
      vehicleClass: (json['vehicleClass'] as num?)?.toInt() ?? 1,
      amount: (json['amount'] as num?)?.toDouble() ?? 0.0,
      sourceName: json['sourceName'] as String? ?? 'TRB Official Toll Rate Matrix',
      sourceUrl: json['sourceUrl'] as String?,
      effectiveFrom: effectiveDate,
      lastVerified: verifiedDate,
      verificationStatus: status,
      explanation: json['explanation'] as String? ?? '',
    );
  }
}
