// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh69e4iOt1v0fYNgCVy7kSERkU0bkywTI',
    appId: '1:486938285341:web:dab43e69a051b9f1fcfdf4',
    messagingSenderId: '486938285341',
    projectId: 'toll-companion-app',
    authDomain: 'toll-companion-app.firebaseapp.com',
    storageBucket: 'toll-companion-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdOKrsq7X08I4S1ms2l2ytZFp8AkaJAYg',
    appId: '1:486938285341:android:a06b116d23fe3f84fcfdf4',
    messagingSenderId: '486938285341',
    projectId: 'toll-companion-app',
    storageBucket: 'toll-companion-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjr0GnGsoitme_ljzdinivrEWVHGDthjA',
    appId: '1:486938285341:ios:65b07dc49ce4ca2bfcfdf4',
    messagingSenderId: '486938285341',
    projectId: 'toll-companion-app',
    storageBucket: 'toll-companion-app.firebasestorage.app',
    iosBundleId: 'com.example.tollcompanion.tollCompanion',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7pgJmYPmr8cAtpGs1de_xC0R9QBKwr7o',
    appId: '1:206412196142:ios:7ab2e784bb19553a6cb2bf',
    messagingSenderId: '206412196142',
    projectId: 'sarge-4586f',
    storageBucket: 'sarge-4586f.firebasestorage.app',
    iosBundleId: 'com.example.tollcompanion.tollCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh69e4iOt1v0fYNgCVy7kSERkU0bkywTI',
    appId: '1:486938285341:web:3bf5536e0c13b77bfcfdf4',
    messagingSenderId: '486938285341',
    projectId: 'toll-companion-app',
    authDomain: 'toll-companion-app.firebaseapp.com',
    storageBucket: 'toll-companion-app.firebasestorage.app',
  );
}
